#!/bin/bash

pwd

# mkdir DBMS 2>> ./.error.log
#  echo -e "Enter Choice: \c"
# read ch
  
PS3="Select a choice: "
  select dbselector in "Create Database" "List Database" "Connect Database" "Drop Database" "exit"
do  
   case $REPLY in
    1) bash ./dbfunc/dbcr ;;
    2) bash ./dbfunc/dbls ;;
    3) bash ./dbfunc/dbcnn ;;
    4) bash ./dbfunc/dbdrp ;;
    5) exit ;;
    *) echo " Wrong Choice " ; bash main ;;
  esac
done