#!/bin/bash

pwd

# mkdir DBMS 2>> ./.error.log
#  echo -e "Enter Choice: \c"
# read ch
  
PS3="Select a choice: "
  select dbselector in "List Database" "Create Database" "Drop Database" "Connect Database" "exit"
do  

   case $REPLY in
    1) bash ./dbfunc/dbls ;;
    2) bash ./dbfunc/dbcr ;;
    3) bash ./dbfunc/dbdrp ;;
    4) bash ./dbfunc/dbcnn ;;
    5) exit ;;
    *) echo " Wrong Choice " ; mainMenu;
  esac
done