#!/bin/bash
PS3="Select a choice: "
select tabselector in "Show Existing Tables " "Create New Table" "Select From Table" "Select From Table" "Update Table" "Delete From Table" "Drop Table" "Back To Main Menu" "Exit"
do 
  case $REPLY in
    1) bash tabfunc/tabls  ;;
    2) bash tabfunc/tabadd ;;
    3) bash tabfunc/tabins ;;
    4) bash tabfunc/tabsel ;;
    5) bash tabfunc/tabupd ;;
    6) bash tabfunc/tabdel ;;
    7) bash tabfunc/tabdrp ;;
    8) bash main ;;
    9) exit ;;
    *) echo " Wrong Choice " ; tabsmenu;
  esac
done