#!/bin/bash
  echo -e "Enter Table Name: \c"
  read tName
  rm $tName .$tName 2>/dev/null
  if [[ $? == 0 ]]
  then
    echo "Table Dropped Successfully"
  else
    echo "Error Dropping Table $tName"
  fi