#!/bin/bash
  echo -e "Enter Database Name: \c"
  read dbName
  cd ./DBMS/$dbName 2>>./.error.log
  if [[ $? == 0 ]]; then
    echo "Database $dbName was Successfully Selected"
    bash main tablesMenu()
  else
    echo "Database $dbName wasn't found"
    bash main
  fi
bash main